version: '3.9'
services:
  db:
    image: postgres:16
    container_name: opensock-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: opensock
      POSTGRES_USER: opensock
      POSTGRES_PASSWORD: opensock
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:

